GROUP=io.github.servetarslan02
VERSION_NAME=1.2.0

POM_URL=https://github.com/servetarslan02/hooksniff-kotlin
POM_SCM_URL=git@github.com:servetarslan02/hooksniff-kotlin.git
POM_SCM_CONNECTION=scm:git:git@github.com:servetarslan02/hooksniff-kotlin.git
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:servetarslan02/hooksniff-kotlin.git
POM_LICENCE_NAME=The MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=servetarslan02
POM_DEVELOPER_NAME=Servet Arslan
POM_DEVELOPER_EMAIL=servetarslan02@gmail.com

POM_DESCRIPTION=HookSniff webhooks Kotlin API client and webhook verification library
POM_NAME=hooksniff-kotlin
POM_ARTIFACT_ID=hooksniff-sdk-kotlin
POM_PACKAGING=jar
POM_ORGANIZATION_URL=https://hooksniff.vercel.app

VENDOR_NAME=HookSniff (https://hooksniff.vercel.app)
